python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '11SaratogaSprings'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '12Southampton'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '13Buffalo'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '14Lockport'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '15Cambria'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '16North Elba'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '17Franklin'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '18Kingston'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '19Wellsville'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '20Kiantone'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '21Olive'
python move2.py --data_path '/data/dailei/WHUGeoGen_v2/Blip2_caption' --destination_path '/data/dailei/WHUGeoGen3' --data_name 'NewYork' --block_name '22Dickinson'
