#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data512/high/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data512/high/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data512/mid/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data512/mid/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data512/low/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data512/low/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#
#
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data1024/high/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data1024/high/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data1024/mid/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data1024/mid/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data1024/low/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data1024/low/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data2048/high/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data2048/high/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data2048/mid/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data2048/mid/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/finetune/data2048/low/RS_images/BeiJing" "/data/dailei/WHUGeoGen3/finetune/data2048/low/RS_images/BeiJing/all_meta_clean.json" --full_path --recursive

python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/pretrain/data768/high/RS_images/NewYork" "/data/dailei/WHUGeoGen3/pretrain/data768/high/RS_images/NewYork/all_meta_clean.json" --full_path --recursive
python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/pretrain/data768/mid/RS_images/NewYork" "/data/dailei/WHUGeoGen3/pretrain/data768/mid/RS_images/NewYork/all_meta_clean.json" --full_path --recursive
python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/pretrain/data768/low/RS_images/NewYork" "/data/dailei/WHUGeoGen3/pretrain/data768/low/RS_images/NewYork/all_meta_clean.json" --full_path --recursive


python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/pretrain/data1280/high/RS_images/NewYork" "/data/dailei/WHUGeoGen3/pretrain/data1280/high/RS_images/NewYork/all_meta_clean.json" --full_path --recursive
python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/pretrain/data1280/mid/RS_images/NewYork" "/data/dailei/WHUGeoGen3/pretrain/data1280/mid/RS_images/NewYork/all_meta_clean.json" --full_path --recursive
python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/pretrain/data1280/low/RS_images/NewYork" "/data/dailei/WHUGeoGen3/pretrain/data1280/low/RS_images/NewYork/all_meta_clean.json" --full_path --recursive

#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/low/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/low/RS_images/all_meta_clean.json"  --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/mid/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/mid/RS_images/all_meta_clean.json"  --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/high/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/high/RS_images/all_meta_clean.json"  --full_path --recursive

#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/low/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/low/RS_images/all_meta_clean.json"  --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/mid/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/mid/RS_images/all_meta_clean.json"  --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/high/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/high/RS_images/all_meta_clean.json"  --full_path --recursive
#
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/low/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/low/RS_images/all_meta_clean.json"  --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/mid/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/mid/RS_images/all_meta_clean.json"  --full_path --recursive
#python ./finetune/merge_all_to_metadata.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/high/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/high/RS_images/all_meta_clean.json"  --full_path --recursive
#



#
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/low/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/low/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/low/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/mid/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/mid/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/mid/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/high/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/high/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Airport/high/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/low/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/low/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/low/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/mid/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/mid/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/mid/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/high/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/high/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Port/high/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/low/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/low/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/low/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/mid/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/mid/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/mid/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/high/RS_images" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/high/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen3/Object_focus/pretrain/Tank/high/RS_images/all_meta_lat_512.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512" --full_path --recursive

#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen2/data1024/high/BeiJing/11SaratogaSprings/RS_images" "/data/dailei/WHUGeoGen2/data1024/high/BeiJing/11SaratogaSprings/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen2/data1024/high/BeiJing/11SaratogaSprings/RS_images/meta_lat.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "1024,1024"
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen2/data1024/mid/BeiJing/11SaratogaSprings/RS_images" "/data/dailei/WHUGeoGen2/data1024/mid/BeiJing/11SaratogaSprings/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen2/data1024/mid/BeiJing/11SaratogaSprings/RS_images/meta_lat.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "1024,1024"
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen2/data1024/low/BeiJing/11SaratogaSprings/RS_images" "/data/dailei/WHUGeoGen2/data1024/low/BeiJing/11SaratogaSprings/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen2/data1024/low/BeiJing/11SaratogaSprings/RS_images/meta_lat.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "1024,1024"
#
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen2/data512/high/BeiJing/11SaratogaSprings/RS_images" "/data/dailei/WHUGeoGen2/data512/high/BeiJing/11SaratogaSprings/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen2/data512/high/BeiJing/11SaratogaSprings/RS_images/meta_lat.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512"
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen2/data512/mid/BeiJing/11SaratogaSprings/RS_images" "/data/dailei/WHUGeoGen2/data512/mid/BeiJing/11SaratogaSprings/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen2/data512/mid/BeiJing/11SaratogaSprings/RS_images/meta_lat.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512"
#python ./finetune/prepare_buckets_latents.py "/data/dailei/WHUGeoGen2/data512/low/BeiJing/11SaratogaSprings/RS_images" "/data/dailei/WHUGeoGen2/data512/low/BeiJing/11SaratogaSprings/RS_images/all_meta_clean.json" "/data/dailei/WHUGeoGen2/data512/low/BeiJing/11SaratogaSprings/RS_images/meta_lat.json" "/home/user/dailei/Code_4090/sd-scripts-0.8.7/models/sd_xl_base_1.0.safetensors" --batch_size 4 --max_resolution "512,512"

