#[prompt]
#width = 1024
#height = 1024
#scale = 7
#sample_steps = 28
#[[prompt.subset]]
#prompt = "1girl, aqua eyes, baseball cap, blonde hair, closed mouth, earrings, green background, hat, hoop earrings, jewelry, looking at viewer, shirt, short hair, simple background, solo, upper body, yellow shirt"
#

[prompt]
width = 512
height = 512
scale = 4
sample_steps = 28
[[prompt.subset]]
prompt = "satellite image,cityscape,outdoors,no humans,scenery,arial view,outdoor"

