[sdxl_arguments]
cache_text_encoder_outputs = false
#cache_image_encoder_outputs = true
#cache_image_encoder_inputs = true
no_half_vae = true
min_timestep = 0
max_timestep = 1000
shuffle_caption = false

[model_arguments]
pretrained_model_name_or_path = "/home/user/dailei/Code_4090/sd-scripts-0.8.7/outputs/SDXL_BJ_NY/sdxl_bj_ny.safetensors"

[dataset_arguments]
debug_dataset = false
token_warmup_min = 1
token_warmup_step = 0
dataset_config = "./train_config/XL_config/dataset_config_example_focus.toml"

[training_arguments]
output_dir = "./outputs/SDXL_focus"
output_name = "sdxl_focus"
save_precision = "fp16"
save_every_n_epochs = 1
#save_last_n_epochs = 1
train_batch_size = 16
max_token_length = 225
mem_eff_attn = false
sdpa = true
xformers = true
#max_train_epochs = 10
max_train_epochs = 5
max_data_loader_n_workers = 16
persistent_data_loader_workers = true
gradient_checkpointing = true
gradient_accumulation_steps = 1
mixed_precision = "fp16"

[logging_arguments]
log_with = "tensorboard"
logging_dir = "./outputs/SDXL_focus/logs"
log_prefix = "sdxl_focus"

[sample_prompt_arguments]
sample_every_n_epochs = 1
sample_sampler = "euler_a"

[saving_arguments]
save_model_as = "safetensors"
save_state = false
resume = ""

[optimizer_arguments]
optimizer_type = "AdaFactor"
learning_rate = 1e-6
max_grad_norm = 0
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False",]
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 100

#[additional_network_arguments]
#no_metadata = false
#network_module = "networks.lora"
#network_dim = 64
#network_alpha = 32
#network_args = [ "conv_dim=32", "conv_alpha=16",]
#network_train_unet_only = true

[advanced_training_config]
