pretrained_model_name_or_path = "/home/wyd-7/dailei/code/0000_2023_Paper1/02_methods/SDXL-Train/models/sd_xl_base_1.0.safetensors"
max_train_epochs = 12
max_data_loader_n_workers = 4
persistent_data_loader_workers = true
seed = 42
gradient_checkpointing = true
mixed_precision = "bf16"
save_precision = "bf16"
full_bf16 = true
optimizer_type = "adamw8bit"
learning_rate = 2e-4
xformers = true
output_dir = "/home/wyd-7/dailei/code/0000_2023_Paper1/02_methods/SDXL-Train/outputs/ControlLLLite"
output_name = "sdxl_controllllite"
save_every_n_epochs = 1
save_model_as = "safetensors"
vae_batch_size = 4
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
network_dim = 64
cond_emb_dim = 32
dataset_config = "/home/wyd-7/dailei/code/0000_2023_Paper1/02_methods/SDXL-Train/train_config/XL_ControlLLLite_congfig/sample_prompt.toml"